apiVersion: v1
kind: Service
metadata:
  name: todo-ai-agent
  namespace: {{ include "todo-app.namespace" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app: todo-ai-agent